<?php
/**
 * Cookie policy tables, generated by [px_cookie_policy].
 *
 * One section per category, one block per service: who runs it, what for, on
 * what legal basis, which cookies it stores and for how long, and where its
 * privacy policy is (art. 13 GDPR). The heading level starts at h2, so the
 * shortcode fits under the h1 of the page.
 *
 * Override: yourtheme/px-shop-core/consent/policy.php
 *
 * @var array $args {
 *     @type array $categories Consent categories.
 *     @type array $grouped    Services grouped by category.
 * }
 *
 * @package PxShopCore
 */

defined( 'ABSPATH' ) || exit;

$categories = isset( $args['categories'] ) ? (array) $args['categories'] : array();
$grouped    = isset( $args['grouped'] ) ? (array) $args['grouped'] : array();
?>
<div class="px-cookie-policy">

	<?php foreach ( $categories as $px_cat_id => $px_cat ) : ?>
		<?php
		$px_services = isset( $grouped[ $px_cat_id ] ) ? $grouped[ $px_cat_id ] : array();

		if ( ! $px_services ) {
			continue;
		}

		$px_locked = ! empty( $px_cat['locked'] );
		?>
		<section class="px-cookie-policy__group" id="px-cookies-<?php echo esc_attr( $px_cat_id ); ?>">

			<h2 class="px-cookie-policy__title"><?php echo esc_html( $px_cat['name'] ); ?></h2>
			<p class="px-cookie-policy__desc"><?php echo esc_html( $px_cat['desc'] ); ?></p>

			<?php foreach ( $px_services as $px_id => $px_service ) : ?>
				<article class="px-cookie-policy__service" id="px-cookies-<?php echo esc_attr( $px_id ); ?>">

					<h3 class="px-cookie-policy__service-name"><?php echo esc_html( $px_service['name'] ); ?></h3>

					<dl class="px-cookie-policy__meta">
						<?php if ( $px_service['purpose'] ) : ?>
							<dt><?php esc_html_e( 'Purpose', 'px-shop-core' ); ?></dt>
							<dd><?php echo esc_html( $px_service['purpose'] ); ?></dd>
						<?php endif; ?>

						<?php if ( $px_service['provider'] ) : ?>
							<dt><?php esc_html_e( 'Provider', 'px-shop-core' ); ?></dt>
							<dd><?php echo esc_html( $px_service['provider'] ); ?></dd>
						<?php endif; ?>

						<dt><?php esc_html_e( 'Legal basis', 'px-shop-core' ); ?></dt>
						<dd>
							<?php
							echo $px_locked
								? esc_html__( 'Necessary for the service you asked for - no consent needed', 'px-shop-core' )
								: esc_html__( 'Your consent, which you can withdraw at any time', 'px-shop-core' );
							?>
						</dd>

						<?php if ( $px_service['privacy'] ) : ?>
							<dt><?php esc_html_e( 'Privacy policy', 'px-shop-core' ); ?></dt>
							<dd><a href="<?php echo esc_url( $px_service['privacy'] ); ?>" target="_blank" rel="noopener nofollow"><?php echo esc_html( $px_service['privacy'] ); ?></a></dd>
						<?php endif; ?>
					</dl>

					<?php if ( $px_service['cookies'] ) : ?>
						<table class="px-cookie-policy__table">
							<caption class="px-cookie-policy__caption">
								<?php
								printf(
									/* translators: %s: service name. */
									esc_html__( 'Cookies stored by %s', 'px-shop-core' ),
									esc_html( $px_service['name'] )
								);
								?>
							</caption>
							<thead>
								<tr>
									<th scope="col"><?php esc_html_e( 'Name', 'px-shop-core' ); ?></th>
									<th scope="col"><?php esc_html_e( 'Expiry', 'px-shop-core' ); ?></th>
									<th scope="col"><?php esc_html_e( 'Purpose', 'px-shop-core' ); ?></th>
								</tr>
							</thead>
							<tbody>
								<?php foreach ( $px_service['cookies'] as $px_cookie ) : ?>
									<tr>
										<td data-px-label="<?php esc_attr_e( 'Name', 'px-shop-core' ); ?>"><code><?php echo esc_html( $px_cookie['name'] ); ?></code></td>
										<td data-px-label="<?php esc_attr_e( 'Expiry', 'px-shop-core' ); ?>"><?php echo esc_html( isset( $px_cookie['expiry'] ) ? $px_cookie['expiry'] : '' ); ?></td>
										<td data-px-label="<?php esc_attr_e( 'Purpose', 'px-shop-core' ); ?>"><?php echo esc_html( isset( $px_cookie['desc'] ) ? $px_cookie['desc'] : '' ); ?></td>
									</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					<?php endif; ?>

				</article>
			<?php endforeach; ?>

		</section>
	<?php endforeach; ?>

	<p class="px-cookie-policy__actions">
		<button type="button" class="px-consent__btn px-consent__btn--settings px-cookie-policy__button" data-px-consent-settings>
			<?php esc_html_e( 'Change cookie settings', 'px-shop-core' ); ?>
		</button>
	</p>

</div>
